export const FOODIO_KITCHEN_RESTAURANT_ID =
  "0f4a0c8e-3d1a-4ef5-8c95-5ee5463a7f01"

export const foodioStudiosDemoProfile = {
  name: "Food.io Studios Demo Home Page",
  username: "foodio_studios_demo",
  email: "foodio.studios.demo@example.com",
  password: "TEST 123",
} as const

export const foodioKitchenRestaurant = {
  name: "FoodIO Kitchen",
  phone: "+91 98765 43210",
  email: "kitchen@foodio.example.com",
  address: "FoodIO Studios, Bengaluru, Karnataka, India",
  resmaplatitude: 12.9716,
  resmaplongitude: 77.5946,
  cuisineTypes: "Indian, Italian, Chinese, Cafe",
  description: "A demo menu for the FoodIO customer experience.",
  status: "ACTIVE" as const,
} as const

export const foodioKitchenMenuItems = [
  {
    name: "Masala Dosa",
    description: "Crisp dosa with potato masala, coconut chutney, and sambar.",
    priceInPaise: 18900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["OTHER"],
    cuisines: ["SOUTH_INDIAN"],
    timings: ["BREAKFAST"],
    caloriesKcal: 420,
  },
  {
    name: "Idli Sambar",
    description: "Steamed rice cakes with sambar and fresh coconut chutney.",
    priceInPaise: 14900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["OTHER"],
    cuisines: ["SOUTH_INDIAN"],
    timings: ["BREAKFAST"],
    caloriesKcal: 280,
  },
  {
    name: "Paneer Paratha",
    description: "Whole-wheat flatbread stuffed with spiced paneer and herbs.",
    priceInPaise: 17900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["OTHER"],
    cuisines: ["NORTH_INDIAN"],
    timings: ["BREAKFAST"],
    caloriesKcal: 390,
  },
  {
    name: "Paneer Tikka Wrap",
    description:
      "Smoky paneer, peppers, onions, and mint chutney in a soft wrap.",
    priceInPaise: 24900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["ROLLS"],
    cuisines: ["NORTH_INDIAN"],
    timings: ["LUNCH", "DINNER"],
    caloriesKcal: 510,
  },
  {
    name: "Crispy Chicken Burger",
    description:
      "Crispy chicken, lettuce, pickles, and house sauce in a toasted bun.",
    priceInPaise: 32900,
    isVeg: false,
    isAvailable: true,
    isActive: true,
    foodTypes: ["BURGER"],
    cuisines: ["OTHER"],
    timings: ["LUNCH", "DINNER"],
    caloriesKcal: 680,
  },
  {
    name: "Margherita Pizza",
    description: "Stone-baked pizza with tomato, mozzarella, and basil.",
    priceInPaise: 34900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["PIZZA"],
    cuisines: ["ITALIAN"],
    timings: ["ALL_DAY"],
    caloriesKcal: 620,
  },
  {
    name: "Chicken Pepperoni Pizza",
    description:
      "Stone-baked pizza with chicken pepperoni, tomato, and mozzarella.",
    priceInPaise: 42900,
    isVeg: false,
    isAvailable: true,
    isActive: true,
    foodTypes: ["PIZZA"],
    cuisines: ["ITALIAN"],
    timings: ["LUNCH", "DINNER"],
    caloriesKcal: 760,
  },
  {
    name: "Creamy Tomato Pasta",
    description:
      "Penne in a roasted tomato cream sauce with parmesan and basil.",
    priceInPaise: 29900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["PASTA"],
    cuisines: ["ITALIAN"],
    timings: ["LUNCH", "DINNER"],
    caloriesKcal: 590,
  },
  {
    name: "Vegetable Hakka Noodles",
    description:
      "Wok-tossed noodles with seasonal vegetables and soy dressing.",
    priceInPaise: 27900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["OTHER"],
    cuisines: ["CHINESE"],
    timings: ["LUNCH", "DINNER"],
    caloriesKcal: 480,
  },
  {
    name: "Chicken Biryani",
    description:
      "Fragrant basmati rice layered with chicken, saffron, and spices.",
    priceInPaise: 37900,
    isVeg: false,
    isAvailable: true,
    isActive: true,
    foodTypes: ["BIRYANI"],
    cuisines: ["NORTH_INDIAN"],
    timings: ["LUNCH", "DINNER"],
    caloriesKcal: 720,
  },
  {
    name: "Vegetable Momos",
    description:
      "Steamed dumplings filled with vegetables and served with chilli dip.",
    priceInPaise: 21900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["MOMOS"],
    cuisines: ["CHINESE"],
    timings: ["ALL_DAY"],
    caloriesKcal: 360,
  },
  {
    name: "Grilled Vegetable Sandwich",
    description: "Grilled sourdough with vegetables, cheese, and herb spread.",
    priceInPaise: 22900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["SANDWICH"],
    cuisines: ["OTHER"],
    timings: ["ALL_DAY"],
    caloriesKcal: 430,
  },
  {
    name: "Garden Salad",
    description:
      "Crisp greens, cucumber, tomato, corn, and lemon herb dressing.",
    priceInPaise: 19900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["SALAD"],
    cuisines: ["OTHER"],
    timings: ["ALL_DAY"],
    caloriesKcal: 190,
  },
  {
    name: "Chocolate Brownie",
    description:
      "Warm chocolate brownie with a soft centre and dark chocolate chunks.",
    priceInPaise: 15900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["DESSERT"],
    cuisines: ["OTHER"],
    timings: ["ALL_DAY"],
    caloriesKcal: 410,
  },
  {
    name: "Gulab Jamun",
    description: "Soft milk dumplings soaked in cardamom and saffron syrup.",
    priceInPaise: 12900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["DESSERT"],
    cuisines: ["NORTH_INDIAN"],
    timings: ["ALL_DAY"],
    caloriesKcal: 290,
  },
  {
    name: "Masala Lime Soda",
    description: "Fresh lime, soda, black salt, and a little spice.",
    priceInPaise: 9900,
    isVeg: true,
    isAvailable: true,
    isActive: true,
    foodTypes: ["DRINKS"],
    cuisines: ["OTHER"],
    timings: ["ALL_DAY"],
    caloriesKcal: 80,
  },
] as const
